logging:
  level: INFO
  loggers:
    "mylogger":
      level: DEBUG
      additive: false
      appenders:
        - type: file
          currentLogFilename: ./log/mylogger.log
          archivedLogFilenamePattern: ./log/mylogger-%d.log.gz
          archivedFileCount: 5
  appenders:
    - type: console

database:
  driverClass: com.mysql.cj.jdbc.Driver
  user: root
  password: password
  #  user: admin
  #  password: admin123
  #  url: jdbc:mysql://localhost:3306/dropwizschema?createDatabaseIfNotExist=true
  url: jdbc:mysql://localhost:3306/dropwizschema?autoReconnect=true&useSSL=false

  maxWaitForConnection: 1s
  validationQuery: "/* MyApplication Health Check */ SELECT 1"
  minSize: 8
  maxSize: 32
  checkConnectionWhileIdle: false
  properties:
    charSet: UTF-8
    hibernate.dialect: org.hibernate.dialect.MySQL5InnoDBDialect
    hibernate.show_sql: true
    hibernate.hbm2ddl.auto: update